# Generated by Django 5.2 on 2025-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Hotel')),
                ('lugar', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Noche')),
                ('estrellas', models.PositiveIntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], verbose_name='Estrellas')),
                ('link_foto', models.URLField(blank=True, max_length=255, null=True, verbose_name='Enlace de la Foto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
