# Generated by Django 5.2 on 2025-05-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('link_foto', models.URLField(blank=True, null=True, verbose_name='Link foto')),
            ],
        ),
    ]
