# Generated by Django 5.1.7 on 2025-03-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='tittle',
            field=models.CharField(max_length=200),
        ),
    ]
