-- Creando la base de datos

CREATE DATABASE <Ejemplo>;

CREATE TABLE User(
    id INT AUTO_INCREMENT PRIMARY KEY,
    status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'INACTIVE',
    username VARCHAR(50) UNIQUE NOT NULL,
    mail VARCHAR(100) UNIQUE NOT NULL,
    age INT UNSIGNED NOT NULL,
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);